### ISSUE TITLE
Mold 한글 변환시 기능 일부 오류 발생

### ISSUE THREAD

**Issue by qoxown12** [ablecloud-team/ablestack-cloud#17]
이미지 > 템플릿 메뉴에서

템플릿 권한 업데이트 팝업 기능에서

번역으로 인한 오류 발생

오류 메시지는 아래와 같습니다.
요청 실패 (431)
Invalid operation on accounts, the operation must be either 'add' or 'remove' in order to modify launch permissions. Given operation is: ' '

**Comment by Dajeong-Park** [comment]
해당 이슈는 수정하여 21년 4월23일자로 merge 되었습니다.
