### ISSUE TITLE
Zone 구성 마법사 오류(기본 스토리지 옵션 누락)

### ISSUE THREAD

**Issue by leca777** [ablecloud-team/ablestack-cloud#20]
초기 Zone 구성 마법사에서 기본 스토리지 구성 시 제공자(provider)항목이 없음에 따라 생성 시 오류가 발생
마법사가 아닌 인프라스트럭처의 기본스토리지 메뉴에서는 제공자 항목이 필수로 입력하게 되어 있어서 정상적으로 생성이 됨

**Comment by Dajeong-Park** [comment]
Zone 구성 마법사 (기본 스토리지 구성) 소스 분석
-  CreateStoragePool API를 통해 전달되며, StorageManagerImpl.java 의 createPool() 에서 provider 파라미터가 null인 경우 DefaultPrimary로 설정하도록 되어있습니다.

        String providerName = cmd.getStorageProviderName();
        DataStoreProvider storeProvider = _dataStoreProviderMgr.getDataStoreProvider(providerName);

        if (storeProvider == null) {
            storeProvider = _dataStoreProviderMgr.getDefaultPrimaryDataStoreProvider();
            if (storeProvider == null) {
                throw new InvalidParameterValueException("can't find storage provider: " + providerName);
            }
        }
- CreateStoragePoolCmd.java 의 API 에서 provider 파라미터는 선택 옵션으로 확인됩니다.

      @Parameter(name = ApiConstants.PROVIDER, type = CommandType.STRING, required = false, description = "the storage provider name")
       private String storageProviderName;

**Comment by Dajeong-Park** [comment]
bronto 업데이트 후 Zone 구성 마법사 테스트 시 정상적으로 완료됨을 확인하였습니다.

**Comment by Dajeong-Park** [comment]
**수정된 이슈 링크** 
https://github.com/apache/cloudstack/pull/4909/files 

해당 소스 Allo 브랜치로 merge 예정
