### ISSUE TITLE
호스트 장애시 HA 기능 미작동

### ISSUE THREAD

**Issue by leca777** [ablecloud-team/ablestack-cloud#23]
host 장애 발생 시 장애 호스트의 상태가 down 이 아닌  alert 상태로 변경되어 정상적으로 HA가 진행되지 않는 현상

host의 상태가 fenced가 되지 않아 가상머신 마이그레이션이 되지 않음(기존 있었던 이슈)

**Comment by Dajeong-Park** [comment]
@Dajeong-Park
