### ISSUE TITLE
CentOS 8.4 Mold 빌드 및 패키징 테스트

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cloud#31]
#### 이슈 타입

 * 문서 보고서

#### 컴포넌트 이름

~~~
BUILD, PACKAGE
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~
CentOS 8.4, CloudStack 4.17.0v
~~~

#### 이슈 내용

기존 빌드 및 패키징 시 Python2, Python3 혼합하여 사용했지만, Python3으로 변경된 소스가 병합되어 CentOS 8.4 환경에서 빌드 및 패키징 테스트를 진행

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by Dajeong-Park** [comment]
**CentOS 8.4 에서 CloudStack 4.16.0v 빌드**

1. extra 패키지 설치
```
	# dnf -y install java-11-openjdk java-11-openjdk-devel git wget tar mkisofs bzip2
```

2. nodejs 설치
```
	# curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
	# dnf install nodejs -y
	# npm install -g @vue/cli npm-check-updates
```

3. maven 설치 및 환경변수 설정
```
	# wget http://www.us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
	# tar -zxvf apache-maven-3.6.3-bin.tar.gz -C /usr/local
	# cd /usr/local
	# ln -s apache-maven-3.6.3 maven
	# echo export M2_HOME=/usr/local/maven >> ~/.bashrc
	# echo export PATH=/usr/local/maven/bin:${PATH} >> ~/.bashrc
	# echo export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.9.11-3.el8_3.x86_64 >> ~/.bashrc
	# source ~/.bashrc
```
4. Python alias 설정
```
        # vi ~/.bashrc 
                      alias python=/usr/bin/python3 
        # source ~/.bashrc
```
5. 소스 다운로드 및 브랜치 설정
```
	# cd /root
	# git clone https://github.com/ablecloud-team/ablestack-cloud.git
	# git clone https://github.com/rhtyd/cloudstack-nonoss.git

	# cd ~/ablestack-cloud
	# git branch
```

6. non-oss 스크립트 실행
```
	# cp ~/cloudstack-nonoss/* ~/ablestack-cloud/deps/
	# overwrite ? y

	# cd ~/ablestack-cloud/deps
	# ./install-non-oss.sh
```

7. 소스 빌드
```	
	# cd ~/ablestack-cloud
	# mvn clean install -P developer -P systemvm -Dnoredist -Dsimulator 
```

**Comment by Dajeong-Park** [comment]
**빌드 이슈**

 * cloud-apidoc 에서 발생하는 jenkins-ci 에러
      1) pom.xml 파일의 745, 752 line의 repo.jenkins-ci 링크를 https로 변경 
              : 해당 수정사항은 CloudStack 소스에 반영되었지만, Ablestack-cloud 에 반영되지않아서 발생하는 오류

      2) /root/ablestack-cloud/tools/apidoc/build-apidoc.sh 파일의 python을 python3로 변경
              : python으로 alias를 지정해도 python 명령어가 실행되지않아 발생하는 오류로 python3로 명시해줌


*  cloud-marvin 에서 발생하는 python cmd 에러
      1) /root/ablestack-cloud/tools/marvin/marvin/codegenerator.py 파일을 CloudStack 최신 소스로 변경
              : 해당 수정사항은 ablestack-cloud에 소스가 병합되지않아 발생하는 오류

      2) /root/ablestack-cloud/tools/marvin/pom.xml의 python을 python3으로 변경
              : python으로 alias를 지정해도 python 명령어가 실행되지않아 발생하는 오류로 python3로 명시해줌

      3) /root/ablestack-cloud/tools/marvin/mvn-setup.py의 python을 python3으로 변경
              : python으로 alias를 지정해도 python 명령어가 실행되지않아 발생하는 오류로 python3로 명시해줌

**Comment by Dajeong-Park** [comment]
**CentOS 8.4 환경에서 CloudStack 4.16.0v 패키징**

1. extra 패키지 설치
```
	# dnf install -y rpm-build gcc glibc-devel              
```

2.  spec 파일 수정
```
	# sed -i 44s/^/#/g /root/ablestack-cloud/packaging/centos8/cloud.spec
	# sed -i 48s/^/#/g /root/ablestack-cloud/packaging/centos8/cloud.spec

	*** 패키지 빌드시 BuildRequires jpackage-utils maven 에러 
		dnf install 명령어로 maven, jpackage-utils 설치 후 진행 가능하지만, 
                             java 1.8 로 down 되며 java, maven 버전 2개씩 존재하게 되어 주석처리 

		jpackage-utils :  Java 패키징을 지원하는 디렉토리 구조, RPM 매크로, 구성 파일 및 스크립트를 설치
```

3. 패키지 빌드
```
	# cd ~/cloudstack/packaging
	# ./package.sh -p noredist -d centos8 -r 1
```

4. RPM파일, 빌드 및 패키징 환경 버전 확인
```
	# ~/cloudstack/dist/rpmbuild/RPMS/x86_64 하위 경로에 RPM파일 확인
	
	java 11.0.11v
	mvn 3.6.3v
	nodejs 12.22.1v
```

**Comment by Dajeong-Park** [comment]
**CentOS 8.4 환경에서 CloudStack 4.16.0v RPM 설치 테스트**

1. cloudstack RPM 설치
```
	Dependency, MySQL, CloudStack RPM 설치
	# rpm -Uvh *.rpm --force
```
2. mysql-server 설정 
```
	# vi /etc/my.cnf
		[mysqld]
		innodb_rollback_on_timeout=1
		innodb_lock_wait_timeout=600
		max_connections=350
		log-bin=mysql-bin
		binlog-format = 'ROW'
	# service mysqld start
	# mysql_secure_installation
```
3. SELinux 설정
```
	# sed -i 's/enforcing/permissive/g' /etc/selinux/config	
	# setenforce permissive
```
4. 스택 DB 설정 및 재시작
```	
	# cloudstack-setup-databases cloud:Ablecloud1! --deploy-as=root:Ablecloud1!
	# cloudstack-setup-management
```
5. 방화벽 설정
```
	# firewall-cmd --permanent --zone=public --add-port=8080/tcp
	# firewall-cmd --permanent --zone=public --add-port=8250/tcp
	# firewall-cmd --permanent --zone=public --add-port=9090/tcp
	# firewall-cmd --reload
	# systemctl enable firewalld
```
6. 웹 접속 및 RPM 설치 후 버전 확인
```
	IP:8080/client 접속
	mysql 8.0.21v
	cloudstack 4.16.0v
```

**Comment by Dajeong-Park** [comment]
위 빌드는 Allo 브랜치로 빌드하였으며, 동일한 환경에서 Bronto 브랜치로 빌드시 이슈

cloud-apidoc 에서 발생하는 jenkins-ci 에러 
 - /root/ablestack-cloud/tools/apidoc/build-apidoc.sh 파일의 python을 python3로 변경

cloud-marvin 에서 발생하는 python cmd 에러 
 - /root/ablestack-cloud/tools/marvin/pom.xml의 python을 python3으로 변경
 - /root/ablestack-cloud/tools/marvin/mvn-setup.py의 python을 python3으로 변경

**Comment by jschoiRR** [comment]
### mac 빌드 환경

(homebrew 설치 후)
1. 기본 패키지 설치 
```
brew install git mysql git python openssh wget
```

2. java openjdk11설치 
```
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk11
java -version (버전 확인)
```

3.  node js 12버전으로 설치(최신 버전으로 설치시 npm install 오류 발생)
```
brew install node@12
node -v  (버전 확인)
```
  

> 제대로_ 설치 안되었을 때(https://nodejs.org/dist/latest-v12.x/) mac 버전 다운로드 후 설치


4. maven 환경 세팅(기존 유닉스 환경과 동일)
```
wget http://www.us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
tar -zxvf apache-maven-3.6.3-bin.tar.gz -C /usr/local
cd /usr/local
ln -s apache-maven-3.6.3 maven
echo export M2_HOME=/usr/local/maven >> ~/.bashrc # or .zshrc or .profile
echo export PATH=/usr/local/maven/bin:${PATH} >> ~/.bashrc # or .zshrc or .profile
source ~/.bashrc
```

5. 소스 다운로드 및 브랜치 설정
```
cd ~ (원하는 위치)
git clone https://github.com/ablecloud-team/ablestack-cloud.git
git clone https://github.com/shapeblue/cloudstack-nonoss.git

cd cloudstack-nonoss
./install-non-oss.sh(서드파티 라이브러리 설치)
```

6. 시뮬레이터, DB 배포
```
cd ablestack-cloud (각자 로컬 위치 확인)
mvn -Pdeveloper -Dsimulator -DskipTests clean install

vi utils/conf/db.properties 파일 수정
=> db.root.password="여기입력"    #  mysql root password값 입력

mvn -Pdeveloper -pl developer -Ddeploydb
mvn -Pdeveloper -pl developer -Ddeploydb-simulator
```

> db password 세팅 오류 시
```
mysql 접속
use mysql;
alter user 'root'@'localhost' identified with mysql_native_password by 'password입력';
flush privileges;
```

> serverTimezone 오류 시
```
vi /opt/homebrew/etc/my.cnf

[mysqld]
default_time_zone='+00:00'

mysql.server restart
```

7. mold 서버 실행
```
mvn -Dsimulator -Dorg.eclipse.jetty.annotations.maxWait=120 -pl :cloud-client-ui jetty:run
```

8. UI 실행
```
cd ui (ablestack-cloud/ui 폴더)
npm install
npm run serve
```

9. 웹 접속
**http://localhost:5050/client**



10. simulate zone, cluster, host, primary storage, secondary storage 환경 구성(marvin 모듈 활용, local에 pip3, python3 설치가 되어 있어야함.)
pip3 install tools/marvin/dist/Marvin-*.tar.gz
python3 tools/marvin/marvin/deployDataCenter.py -i setup/dev/advanced.cfg


11. **http://localhost:5050/client**
- 인프라스트럭쳐 > 존 메뉴 이동 
- 생성된 Zone 활성화
-  가상머신, 네트워크 생성 테스트 진행

**Comment by jschoiRR** [comment]
mvn systemvm 빌드 시 'mkiosfs' 패키지가 필수 맥에서 설치되지 않음.
systemvm 외 api, ui 빌드 가능.

**Comment by Dajeong-Park** [comment]
**Mold 빌드 및 패키징 환경 성능 테스트 결과**

8C16G 가상머신 

사이트 배포시 빌드 옵션 : mvn -T 4C clean install -P developer -Dnoredist -DskipTests
테스트시 빌드 옵션 : mvn -T 4C clean install -P developer -DskipTests (빌드4분 / 패키징11분 = 약15분 소요)

*** 테스트 시 jar파일만 변경한 후 재시작해도 테스트 가능

**Mold Build Server 템플릿** 
- https://images.ablecloud.io/mold_build_server.qcow2
- https://nas.ablecloud.io/web/tmpl/mold_build_server.qcow2

**Mold RPM (allo, gs인증, bronto 버전)**
- 10.10.0.202 /ablecloud/패키지 파일/ablestack-버전(날짜빌드) 폴더로 구분하여 명시

**Comment by sjyu1** [comment]
* CentOS 8.4 에서 CloudStack 4.16.0v 빌드

1. extra 패키지 설치 

이부분에서 **rpmbuild** 추가필요(rpm packaging시 rpmbuild명령어 실행을 위해)


* package.sh 실행시, error /var/www/html/vue-storefront/node_modules/node-sass: Command failed.

1. node 버전 확인(v12.22.7)
$node -v

**Comment by stardom3645** [comment]
다운로드 가능한 maven 3.6.3 링크

wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.6.3/apache-maven-3.6.3-bin.tar.gz

**Comment by stardom3645** [comment]
[에러 처리] pycrypto 설치 에러
 
Rocky Linux 9.3에서 아래 명령어 실행하여 시물레이션 데이터 입력 절차 중 에러 발생할 경우,
"pip3 install tools/marvin/dist/Marvin-*.tar.gz" 

pycrypto 설치 에러 발생 시 아래 코드 실행

```
sudo yum groupinstall 'Development Tools'
sudo yum install python-devel
```

**Comment by sjyu1** [comment]
mac 빌드 환경구성시, python 버전 확인필요  

**버전이 다를 경우 오류사항**
1. mvn 빌드시 cloud-marvin 빌드 오류

```
[INFO] --- exec:1.2.1:exec (package) @ cloud-marvin ---
/Users/yusujeong/Documents/git/ablestack-cloud/tools/marvin/mvn-setup.py:36: SyntaxWarning: invalid escape sequence '\s'
  needle = '\nVERSION\s*=\s*[\'"][^\'"]*[\'"]'
Traceback (most recent call last):
  File "/Users/yusujeong/Documents/git/ablestack-cloud/tools/marvin/setup.py", line 20, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

2. simulate zone 구성오류


**오류사항에 따른 python, pip 버전 확인 및 버전 변경(3.10 이어야함. 그 이상일 경우 오류발생)**
1. python3 -V
`Python 3.10.9`

2. pip3 -V
`pip 22.3.1 from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip (python 3.10)`
