### ISSUE TITLE
Desktop Service - Clusters 상세 화면 및 탭 개발

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cloud#35]
#### 이슈 타입

 * 기능 추가 요청

#### 컴포넌트 이름

~~~
UI
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

Desktop Service > Clusters 메뉴의 목록 중 특정 Cluster 이름 선택 시 상세정보, Details/Networks/IP Range/Control VM/Desktop VM 탭 UI 제공

- [ ] 상세 정보 출력 및 링크 연결             
             상태(Status)
             ID
             네트워크(Network)
             컴퓨트 오퍼링(Compute Offering)
             Zone(Zone)
             계정(Account)
             도메인(Domain)
             링크 연결 : Network 선택시 해당 Network로 연결, Zone 선택시 해당 Zone으로 연결, Account 선택시 해당 Account로 연결, Domain 선택시 해당 Domain으로 연결

- [ ] Details 탭 정보 출력 및 링크 연결
             이름(Name)
             ID
             설명(Description)
             템플릿 버전(Controller Version)
             계정(Account)
             AD 도메인(AD Domain)
             Zone
             Works 포탈 URL
             링크 연결 : Zone 선택시 해당 Zone으로 연결, Account 선택시 해당 Account로 링크 연결, 포탈 URL 선택시 포탈로 연결

- [ ] Networks 탭 정보 출력 
            Network 정보 출력 : Network Name, MAC Address, IP Address, Netmask, Gateway

- [ ] IP Range 탭 정보 출력 및 버튼 추가 (L2 Network일때만 활성화)
            Add IP Range 버튼 추가
            IP Range 정보 출력 : Gateway, Netmask, StartIP, EndIP
            IP Range 액션 삭제 버튼 추가

- [ ] Control VM 탭 정보 출력 및 링크 연결
            Control VM 정보 출력 : 이름, 상태, 내부이름, IP, 호스트
            링크 연결 : Control VM의 이름 선택시 해당 VM으로 링크 연결

- [ ] Desktop VM 탭 정보 출력 및 링크 연결
            Desktop VM 정보 출력 : 이름, 상태, 내부이름, IP, 호스트
            링크 연결 : Desktop VM의 이름 선택시 해당 VM으로 링크 연결

- [ ] 우측 상단 Cluster 상태에 따른 액션 표시 : Enable (비활성화, 삭제, Works 포탈 연결), Disable (활성화, 삭제)

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by Dajeong-Park** [comment]
@Dajeong-Park

**Comment by jschoiRR** [comment]
@jschoiRR
