### ISSUE TITLE
Desktop Service - Desktop Cluster 목록 조회 API 개발

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cloud#44]
#### 이슈 타입

 * 기능 추가 요청

#### 컴포넌트 이름

~~~
UI
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

- [ ] Mold의 Desktop Service의 Cluster 목록 조회 API
            desktop_cluster, desktop_vm_details 테이블 조회
            Works 포탈 연결을 위해 Cluster의 Works VM IP 조회
            Cluster의 Control VM 상태가 모두 Running인 경우 Enable, 하나라도 Stop인 경우 Disable로 상태 업데이트

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by Dajeong-Park** [comment]
@Dajeong-Park

**Comment by jschoiRR** [comment]
@jschoiRR
