### ISSUE TITLE
Desktop Service - Controller Template 버전 추가 API 개발

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cloud#49]
#### 이슈 타입

 * 기능 추가 요청

#### 컴포넌트 이름

~~~
API
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

Desktop Controller Template 버전 추가 API

- [ ] Desktop Controller Templates 등록 
1) Template 등록 
 * 필요 파라미터 : displaytext(설명), format(QCOW2, RAW 등), hypervisor(하이퍼바이저), name(이름), url(URL), ostypeid(OS유형 ID)
2) 태그 추가
 * 필요 파라미터 : resourceids(Template ID), resourcetype(Template), tags(tags[0].key=key, tags[0].value=value)

- [ ] Desktop Controller Templates 관련 DB 업데이트

**개발 시 고려사항**
- 해당 API에 대한 역할은 관리자 권한만 실행가능하도록 구현해야함
- DB 업데이트 시점
- 태그 KEY, VALUE 규칙
- 관리자 권한만 가능하도록 개발되어야함

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by jschoiRR** [comment]
@jschoiRR
