### ISSUE TITLE
Desktop Service - Controller Template 버전 관리/삭제 API 개발

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cloud#50]
#### 이슈 타입

 * 기능 추가 요청

#### 컴포넌트 이름

~~~
API
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

Desktop Controller Template의 액션으로 템플릿 버전 관리, 템플릿 삭제 API 제공

- [ ] Desktop Controller Template 버전 관리 API
         desktop_controller_template 테이블에서 state 를 enable/disable 변경

- [ ] Desktop Controller Template 버전 삭제 API
         desktop_controller_template 테이블에서 선택한 템플릿 삭제, desktop_template_map 테이블에서 연결된 템플릿 삭제

위 API는 관리자 권한만 실행 가능하도록 개발되어야함

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by jschoiRR** [comment]
@jschoiRR
