### ISSUE TITLE
Template 목록 조회 시 Desktop 관련 템플릿의 경우 Zone 탭의 액션 hide 처리

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cloud#52]
#### 이슈 타입

 * 기능 추가 요청

#### 컴포넌트 이름

~~~
UI
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

- [ ] Mold의 이미지 > 템플릿 목록 중 Desktop Controller, Master Templates의 경우 상세화면의 Zone 탭에서 템플릿 복사, 템플릿 삭제 버튼 hide 처리

* Kubernetes ISO 의 경우에도 이미지 > ISOs 목록 중 Kubernetes ISO의 경우 상세 화면의 Zone 탭에 액션은 hide 처리되는 방식과 동일

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by jschoiRR** [comment]
@jschoiRR
