### ISSUE TITLE
Desktop Service - Master Templates 목록 화면 개발

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-cloud#54]
#### 이슈 타입

 * 기능 추가 요청

#### 컴포넌트 이름

~~~
UI
~~~

#### ABLESTACK 버전

~~~
Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

Mold의 Desktop Service > Master Templates 메뉴에서 등록된 Desktop Master Templates 목록을 볼 수 있도록 UI 제공

- [ ] Master Templates 메뉴 추가 및 아이콘 설정
- [ ] Master Templates 버전 이름, 하이퍼바이저, OS 유형, 버전에 대한 정보 출력
- [ ] Master Templates 버전 + 버튼 추가
- [ ] Master Templates 액션 표시 : 템플릿 버전 관리, 템플릿 삭제
- [ ] 검색 필터링
- [ ] 링크 연결 : Master Templates 이름 선택시 Master Templates 상세화면으로 연결

#### 재현 과정

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by jschoiRR** [comment]
@jschoiRR
