### ISSUE TITLE
Wall - 사용자 가상머신 모니터링 팝업 기능

### ISSUE THREAD

**Issue by kt-cheon** [ablecloud-team/ablestack-cloud#68]
#### 이슈 타입

 * 새 기능 아이디어

#### 컴포넌트 이름

~~~

~~~

#### ABLESTACK 버전

~~~
ABLESTACK-Bronto
~~~

#### 구성

~~~

~~~

#### OS / 환경

~~~

~~~

#### 이슈 내용

사용자 가상머신의 모니터링 정보를 Mold(모니터링 버튼 클릭)에서 팝업 형태로 제공

#### 재현 과정

 - grafana panel share의 iframe을 이용한 팝업 형태로 사용자의 가상머신 모니터링

~~~

~~~

#### 기대한 결과

~~~

~~~

#### 실제 결과

~~~

~~~

**Comment by Dajeong-Park** [comment]
Mold 관리자 로그인 시

         1. 메인 화면 우측 상단의 계정 정보 클릭 >  Profile 버튼 아래에 모니터링 버튼 클릭 > 팝업 형태로 Admin 종합대시보드로 연결

Mold 사용자 로그인 시

         1. Compute > Instances 목록의 각 가상머신에 대한 액션 중 모니터링 버튼 클릭 > 팝업 형태로 해당 가상머신에 대한 모니터링 화면 연결
         2. Instance 상세화면의 우측 상단에 해당 가상머신에 대한 액션 중 모니터링 버튼 클릭 > 팝업 형태로 해당 가상머신에 대한 모니터링 화면 연결

**Comment by jschoiRR** [comment]
@jschoiRR
